SELECT 
       a.address,
       b.REVENUE, 
       b.REVENUE - p.COST as MARGIN
FROM TEST_DB.OLTP.BILLINGTRANSACTION b
LEFT JOIN TEST_DB.OLTP.PRODUCT p ON b.PRODUCTID = p.PRODUCTID
LEFT JOIN TEST_DB.OLTP.CUSTOMERADDRESSHISTORY ca ON  b.CUSTOMERID = ca.CUSTOMERID
      AND b.BILLING_DATE BETWEEN ca.EFFECTIVEFROM AND ca.EFFECTIVETO
LEFT JOIN TEST_DB.OLTP.ADDRESS a ON a.ADDRESSID = ca.ADDRESSID