SELECT MONTHNAME(b.BILLING_DATE) as MONTH, 
       p.PRODUCT_NAME, 
       SUM(b.REVENUE), 
       SUM(b.REVENUE - p.COST) as MARGIN
FROM TEST_DB.OLTP.BILLINGTRANSACTION b
LEFT JOIN TEST_DB.OLTP.PRODUCT p ON b.PRODUCTID = p.PRODUCTID
GROUP by MONTHNAME(b.BILLING_DATE),
         p.PRODUCT_NAME

